// <auto-generated />
namespace ReelCheck.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Increasestatuscolumnslength : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Increasestatuscolumnslength));
        
        string IMigrationMetadata.Id
        {
            get { return "201806071344089_Increase status columns length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
